name: Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, MinSizeRel]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest

      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Set strings
        id: strings
        shell: bash
        run: |
          echo "build-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install vcpkg
        uses: actions/checkout@v4
        with:
          repository: "microsoft/vcpkg"
          path: "vcpkg"

      - name: Bootstrap vcpkg
        run: |
          ${{ github.workspace }}/vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential make cmake \
            pkg-config ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
            libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
            libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
            libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
            libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev \
            glslang-tools

      - name: CMake Configure
        run: >
          cmake -G Ninja
          -B ${{ steps.strings.outputs.build-dir }}
          -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
          -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}
          -S ${{ github.workspace }}

      - name: CMake Build
        run: cmake --build ${{ steps.strings.outputs.build-dir }}